/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dam.di_generadorexamenes_claudiamangas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Claudia Mangas
 */
public class ExamenesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ExamenesFrame
     */
    private final int MIN_BEADS = 1;
    private final int MAX_BEAADS = 10;
    private final int MIN_TOPICS = 60;
    private final int MAX_TOPICS = 71;
    private final int INIT_TOPIS = 64;
    private File topics=new File("topics.txt");
    private ArrayList<String> topicList=new ArrayList<>();

    public ExamenesFrame() {
        initComponents();

        //cargarTemasyBolas();
        //agregarTemas();
        //generarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_combo = new javax.swing.JPanel();
        lbl_temas = new javax.swing.JLabel();
        combo_temas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        combo_bolas = new javax.swing.JComboBox<>();
        pnl_footer = new javax.swing.JPanel();
        btn_generate = new javax.swing.JButton();
        btn_clean = new javax.swing.JButton();
        pnl_main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_combo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lbl_temas.setText("Número de temas");
        pnl_combo.add(lbl_temas);

        combo_temas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_temasActionPerformed(evt);
            }
        });
        pnl_combo.add(combo_temas);

        jLabel2.setText("Número de bolas");
        pnl_combo.add(jLabel2);

        combo_bolas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnl_combo.add(combo_bolas);

        getContentPane().add(pnl_combo, java.awt.BorderLayout.PAGE_START);

        btn_generate.setText("Generar");
        btn_generate.setAlignmentX(0.5F);
        btn_generate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });
        pnl_footer.add(btn_generate);

        btn_clean.setText("Limpiar");
        btn_clean.setAlignmentX(0.5F);
        btn_clean.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnl_footer.add(btn_clean);

        getContentPane().add(pnl_footer, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout pnl_mainLayout = new javax.swing.GroupLayout(pnl_main);
        pnl_main.setLayout(pnl_mainLayout);
        pnl_mainLayout.setHorizontalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnl_mainLayout.setVerticalGroup(
            pnl_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        getContentPane().add(pnl_main, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_temasActionPerformed
        int topicNumber = Integer.parseInt((String) combo_temas.getSelectedItem());
        pnl_main.removeAll();
        generateBtns(topicNumber);
    }//GEN-LAST:event_combo_temasActionPerformed


    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed
        int topicNumber=Integer.parseInt((String) combo_temas.getSelectedItem());
        pnl_main.removeAll();
        generateBtns(topicNumber);
        
        int beadNumber = Integer.parseInt((String)combo_bolas.getSelectedItem());
        int componentNumber = pnl_main.getComponentCount();
        
        for (int i = 0; i < beadNumber; i++) {
            int randomBtn = (int) (Math.random()*componentNumber+1);
            while(randomBtn > topicNumber -1){
                randomBtn = (int)(Math.random()*componentNumber+1);
            }
            JButton btnSelected=(JButton) pnl_main.getComponent(randomBtn);
            
            if(btnSelected.isEnabled()){
                boolean isActive = true;
                while(isActive){
                    randomBtn = (int)(Math.random()*componentNumber+1);
                    btnSelected = (JButton) pnl_main.getComponent(randomBtn);
                    if(!btnSelected.isEnabled()){
                        isActive = false;
                    }
                }
            }           
            btnSelected.setEnabled(true);     
        }
    }//GEN-LAST:event_btn_generateActionPerformed

    private void loadTopicsAndBeads(){
        for (int i = MIN_TOPICS; i < MAX_TOPICS; i++) {
            
        }
    }
    
    private void generateBtns(int numTopics) {
        for (int i = 0; i < numTopics; i++) {
            JButton btn_topics=new JButton(String.valueOf(i+1));
            btn_topics.setEnabled(false);
            String topic= topicList.get(i);
            btn_topics.addActionListener(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent e){
                    JOptionPane.showMessageDialog(pnl_main, topic, "Titulo del tema", JOptionPane.INFORMATION_MESSAGE
                    );
                }
            });
            pnl_main.add(btn_topics);
                    
        }
    }
    
    private void addTopics(File topics){
        
        try {
            String line;
            BufferedReader br=new BufferedReader(new FileReader(topics));
            while((line=br.readLine()) != null){
                topicList.add(line);
            }
            br.close();
            
        } catch (FileNotFoundException e) {
            System.out.println("File not found");
        } catch(IOException ex) {
            System.out.println("Error while reading file");
        }
    }
    
    private void setNumExams(){
        new Random().ints((int) combo_bolas.getSelectedItem(),1,(int)combo_temas.getSelectedItem());
        for (String string : topicList) {
           
            // panel.revalidate();
            //panel.repaint();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamenesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamenesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clean;
    private javax.swing.JButton btn_generate;
    private javax.swing.JComboBox<String> combo_bolas;
    private javax.swing.JComboBox<String> combo_temas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_temas;
    private javax.swing.JPanel pnl_combo;
    private javax.swing.JPanel pnl_footer;
    private javax.swing.JPanel pnl_main;
    // End of variables declaration//GEN-END:variables
}
